# Assigning cell cycle phase

```{r, echo=FALSE, results="hide"}
knitr::opts_chunk$set(error=FALSE, message=FALSE, warning=FALSE)
```

```{r, echo=FALSE, results="hide"}
library(BiocStyle)
library(HDF5Array)
library(SummarizedExperiment)
se.out <- readRDS("objects/qc_mat.rds")
```

Here, we use the `cyclone` method to assign cells to the cell cycle phase.
We do so using the pre-trained mouse classifier, and a number of cores to reduce computational time.

```{r}
library(scran)
set.seed(100)
mm.pairs <- readRDS(system.file("exdata", "mouse_cycle_markers.rds", package="scran"))
assigned <- cyclone(assay(se.out, withDimnames=FALSE), mm.pairs, 
                    gene.names=rowData(se.out)$Ensembl, BPPARAM=MulticoreParam(3))
```

Making a plot of the cell cycle scores.

```{r cyclescores}
smoothScatter(assigned$scores$G1, assigned$scores$G2M, 
    xlab="G1 score", ylab="G2M score")
```

We save the phases to the `SummarizedExperiment` object in case it's useful.

```{r}
se.out$phase <- assigned$phase
table(assigned$phase)
```

Saving all of the results to file for later use.

```{r}
saveRDS(assigned, file="objects/cycle_output.rds")
```

```{r echo=FALSE, results="hide"}
# Saving the new object as well.
saveRDS(file="objects/qc_mat.rds", se.out)
```
